# Generated by Django 5.0.6 on 2024-07-10 19:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cls_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_firstname', models.CharField(max_length=50)),
                ('var_lastname', models.CharField(blank=True, max_length=50)),
                ('var_phone', models.CharField(max_length=20)),
                ('var_email', models.EmailField(max_length=254)),
                ('var_createddate', models.DateTimeField(default=django.utils.timezone.now)),
                ('var_description', models.TextField(blank=True)),
            ],
        ),
    ]
