# Generated by Django 5.0.6 on 2024-07-10 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_var_createddate_cls_contact_create_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cls_contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
