# Generated by Django 5.0.6 on 2024-07-10 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_cls_contact_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cls_contact',
            old_name='Create Date',
            new_name='var_createddate',
        ),
        migrations.RenameField(
            model_name='cls_contact',
            old_name='Description',
            new_name='var_description',
        ),
        migrations.RenameField(
            model_name='cls_contact',
            old_name='E-mail',
            new_name='var_email',
        ),
        migrations.RenameField(
            model_name='cls_contact',
            old_name='First Name',
            new_name='var_firstname',
        ),
        migrations.RenameField(
            model_name='cls_contact',
            old_name='Last Name',
            new_name='var_lastname',
        ),
        migrations.RenameField(
            model_name='cls_contact',
            old_name='Phone Number',
            new_name='var_phone',
        ),
    ]
