# Generated by Django 5.0.6 on 2024-07-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_rename_var_firstname_cls_contact_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cls_contact',
            old_name='var_createddate',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='cls_contact',
            old_name='var_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='cls_contact',
            old_name='var_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='cls_contact',
            old_name='var_lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='cls_contact',
            old_name='var_phone',
            new_name='phone',
        ),
    ]
