# Generated by Django 5.0.6 on 2024-07-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_rename_var_createddate_cls_contact_create_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cls_contact',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
