# Generated by Django 5.0.6 on 2024-07-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_rename_create_date_cls_contact_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cls_contact',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='cls_contact',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
